---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: 192.168.210.1
            - name: NFS_PATH
              value: /mnt/8tb
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.210.1
            path: /mnt/8tb
