---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-gpu-exporter
  namespace: kube-tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: intel-gpu-plugin
      namespace: kube-tools
  values:
    controller:
      type: daemonset
    image:
      repository: ghcr.io/onedr0p/intel-gpu-exporter
      tag: rolling@sha256:1511f71b317fa7b7ef297bd2fb27f403800562b3461fc414992c245ee68335e2
    service:
      main:
        ports:
          http:
            port: 8080
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
            relabelings:
              - sourceLabels: [__meta_kubernetes_pod_node_name]
                targetLabel: node
    securityContext:
      privileged: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values: ["true"]
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 100m
        memory: 100Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 500Mi
